CREATE DATABASE web_4a_g1 COLLATE UTF8MB4_GENERAL_CIworld;
USE web_4a_g1;

CREATE TABLE users (
	user_id INT UNSIGNED NOT NULL AUTO_INCREMENT,
	username VARCHAR(100) NOT NULL,
	password VARCHAR(300) NOT NULL,
	birthdate DATE NOT NULL,
	email VARCHAR(100) NOT NULL,
	gender INT NOT NULL
	
	CONSTRAINT user_id_PK PRIMARY KEY(user_id)
)